### ISSUE TITLE
Build prerequisites: the Ubuntu 20.04 python3-cryptography doesn't work

### ISSUE THREAD

**Issue by markz-zhang** [OP-TEE/optee_docs#195]
In the document: https://optee.readthedocs.io/en/latest/building/prerequisites.html, the python package, cryptography, is documented to be installed from Ubuntu package repository.
But in Ubuntu 20.04, python3-cryptography is too old to build the latest optee_os. The build error is like:

```
Traceback (most recent call last):
  File "/home/mohits/temp/bseid_5986093/src_release/nvidia-jetson-optee-source/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 968, in <module>
    main()
  File "/home/mohits/temp/bseid_5986093/src_release/nvidia-jetson-optee-source/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 964, in main
    args.func(args)
  File "/home/mohits/temp/bseid_5986093/src_release/nvidia-jetson-optee-source/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 841, in command_sign_enc
    ta_image.add_subkey(args.subkey, args.name)
  File "/home/mohits/temp/bseid_5986093/src_release/nvidia-jetson-optee-source/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 793, in add_subkey
    sk_image.parse()
  File "/home/mohits/temp/bseid_5986093/src_release/nvidia-jetson-optee-source/optee/build/t234/export-ta_arm64/scripts/sign_encrypt.py", line 562, in parse
    self.subkey_key = rsa.RSAPublicNumbers(e, n).public_key()
TypeError: public_key() missing 1 required positional argument: 'backend'
```

The solution is to install a newer version cryptography:

```
sudo apt remove python3-cryptography
pip3 install cryptography
```

So create this ticket and hope it can be fixed quickly.

**Comment by markz-zhang** [comment]
Can anyone take a look at this issue?
